### ISSUE TITLE
Dependency filter

### ISSUE THREAD

**Issue by OlliZi** [r-cohen/unused-dep#5]
Please provide a feature to filter dependencies to avoid processing them.

For example:

java -jar unused-dep.jar -gradletask :app:assembleDebug 'implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:xyz"'

or

java -jar unused-dep.jar -gradletask :app:assembleDebug "org.jetbrains.kotlin:kotlin-stdlib-jdk8:xyz"

**Comment by raphael-anydo** [comment]
@OlliZi thanks for the idea. I might implement it as follows:
`java -jar unused-dep.jar -gradletask :app:assembleDebug -skip "org.jetbrains.kotlin:kotlin-stdlib-jdk8:xyz","com.mydep:mylib:qwerty"`

**Comment by r-cohen** [comment]
added in v1.1.0
