### ISSUE TITLE
Not able to find the unused dependency.

### ISSUE THREAD

**Issue by PrashantKumarR** [r-cohen/unused-dep#6]
I tried using this tool in a multi module android project. I intentionally put a few dependency which I am not using in the build.gradle file but it reported

NO UNUSED DEPENDENCIES FOUND FOR GRADLE TASK :samplesdkapp:assembleDebug:

**Comment by raphael-anydo** [comment]
@PrashantKumarR 
the dependency detection is only performed on the module specified in the argument when running the tool, in your case `samplesdkapp`. if you want to use it for multiple modules, you'll have to run it for each module: , `:module0:assembleDebug:``:module1:assembleDebug:`, ...,`:samplesdkapp:assembleDebug:`

**Comment by r-cohen** [comment]
@PrashantKumarR
the dependency detection is only performed on the module specified in the argument when running the tool, in your case `samplesdkapp`. if you want to use it for multiple modules, you'll have to run it for each module and for the app module itself: , `:module0:assembleDebug:`, `:module1:assembleDebug:`, ...,`:samplesdkapp:assembleDebug:`

could you confirm the dependencies you added were in a different module than `samplesdkapp`?
